"use client";

import Script from "next/script";

export default function BandsInTownWidget() {
  return (
    <div className="bit-widget-container">
      <Script
        src="https://widgetv3.bandsintown.com/main.min.js"
        strategy="lazyOnload"
      />
      {/* eslint-disable-next-line @next/next/no-html-link-for-pages */}
      <a
        className="bit-widget-initializer"
        data-artist-name="id_15556715"
        data-background-color="rgba(18,15,11,1)"
        data-separator-color="rgba(61,43,31,0.6)"
        data-text-color="rgba(232,213,176,1)"
        data-font="Helvetica"
        data-auto-style="false"
        data-button-label-capitalization="uppercase"
        data-header-capitalization="uppercase"
        data-location-capitalization="uppercase"
        data-venue-capitalization="uppercase"
        data-local-dates-position="tab"
        data-display-details="true"
        data-display-lineup="true"
        data-display-start-time="true"
        data-social-share-icon="false"
        data-display-limit="all"
        data-date-format="MMM. D, YYYY"
        data-date-orientation="horizontal"
        data-date-border-color="rgba(196,98,26,0.5)"
        data-date-border-width="1px"
        data-date-capitalization="capitalize"
        data-date-border-radius="10px"
        data-event-ticket-cta-size="medium"
        data-event-ticket-text="TICKETS"
        data-event-ticket-icon="false"
        data-event-ticket-cta-text-color="rgba(250,246,240,1)"
        data-event-ticket-cta-bg-color="rgba(196,98,26,1)"
        data-event-ticket-cta-border-color="rgba(196,98,26,1)"
        data-event-ticket-cta-border-width="0px"
        data-event-ticket-cta-border-radius="2px"
        data-sold-out-button-text-color="rgba(240,230,208,1)"
        data-sold-out-button-background-color="rgba(61,43,31,1)"
        data-sold-out-button-border-color="rgba(61,43,31,1)"
        data-sold-out-button-clickable="true"
        data-event-rsvp-position="left"
        data-event-rsvp-cta-size="medium"
        data-event-rsvp-only-show-icon="false"
        data-event-rsvp-text="RSVP"
        data-event-rsvp-icon="false"
        data-event-rsvp-cta-text-color="rgba(196,98,26,1)"
        data-event-rsvp-cta-bg-color="rgba(18,15,11,1)"
        data-event-rsvp-cta-border-color="rgba(196,98,26,1)"
        data-event-rsvp-cta-border-width="1px"
        data-event-rsvp-cta-border-radius="2px"
        data-follow-section-position="top"
        data-follow-section-alignment="center"
        data-follow-section-header-text="Get updates on new shows, new music, and more"
        data-follow-section-cta-size="medium"
        data-follow-section-cta-text="FOLLOW"
        data-follow-section-cta-icon="false"
        data-follow-section-cta-text-color="rgba(250,246,240,1)"
        data-follow-section-cta-bg-color="rgba(196,98,26,1)"
        data-follow-section-cta-border-color="rgba(196,98,26,1)"
        data-follow-section-cta-border-width="0px"
        data-follow-section-cta-border-radius="2px"
        data-play-my-city-position="bottom"
        data-play-my-city-alignment="center"
        data-play-my-city-header-text="Don't see a show near you?"
        data-play-my-city-cta-size="medium"
        data-play-my-city-cta-text="REQUEST A SHOW"
        data-play-my-city-cta-icon="false"
        data-play-my-city-cta-text-color="rgba(250,246,240,1)"
        data-play-my-city-cta-bg-color="rgba(61,43,31,1)"
        data-play-my-city-cta-border-color="rgba(61,43,31,1)"
        data-play-my-city-cta-border-width="0px"
        data-play-my-city-cta-border-radius="2px"
        data-language="en"
        data-layout-breakpoint="900"
        data-app-id="853436f326ccce6924dd38ae2f21e973"
        data-bit-logo-position="bottomRight"
        data-bit-logo-color="rgba(92,61,46,1)"
      />
    </div>
  );
}
